# Generated by Django 4.1.5 on 2023-03-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movie_gener_alter_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='gener',
            field=models.CharField(choices=[('action', 'action'), ('comedy', 'comedy'), ('romantic', 'romantic'), ('amharic', 'amharic'), ('drama', 'drama')], default='action', max_length=10),
        ),
    ]
